### ISSUE TITLE
Create the modal popups with information about individual trails when hovering over main map

### ISSUE THREAD

**Issue by aanielson** [lindseypaluso/hikeandforageapp#3]
DO NOT use alerts, confirms, or prompts.

**Comment by lindseypaluso** [comment]
- Small modal per hike on 3 key points of each specific hike -> leads you to more detailed hike page

**Comment by aanielson** [comment]
Megan incorporated modal popups on the plants page. Still would like to have modal popups when hovering on the main map - Lisa is working on it.
