### ISSUE TITLE
Create a polished front end/UI

### ISSUE THREAD

**Issue by lindseypaluso** [lindseypaluso/hikeandforageapp#8]

**Comment by lindseypaluso** [comment]
- Create wireframe: navbar / header / footer + space for map and user validation form

- User validation form with specification checkboxes for hike distance, hike difficulty, plant type available

- List view of hikes with info above as table / repeating element

**Comment by aanielson** [comment]
Wireframe and user validation for zipcode, distance from zip, and number of results. Hike distance and difficulty are displayed, but not validated.
List view/repeating info on hikes is displaying.

Still need: plant type functionality
